import Head from 'next/head';
import { Global, css } from '@emotion/react';
import { ApolloProvider } from '@apollo/client';
import styled from '@emotion/styled';
import Header from '../components/Header';
import Footer from '../components/Footer';
import client from '../apollo-client';

const GlobalStyles = css`
  * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }

  html {
    scroll-behavior: smooth;
  }

  html,
  body {
    height: 100%;
    width: 100%;
  }
`;

const MainSection = styled.main`
  flex-grow: 1;
  margin-top: 80px;
`;

const Wrapper = styled.div`
  display: flex;
  flex-direction: column;
  min-height: 100vh;
`;

function MyApp({ Component, pageProps }) {
  return (
    <Wrapper>
      <Global styles={GlobalStyles} />
      <Head>
        <title>Pokemon App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Google Fonts */}
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link
        rel="preconnect"
        href="https://fonts.gstatic.com"
        crossOrigin="true"
      />
      <link
        href="https://fonts.googleapis.com/css2?family=Karla:wght@300;400;500;600;700;800&family=Source+Sans+Pro:wght@300;400;600;700;900&display=swap"
        rel="stylesheet"
      />
      <Header />

      <ApolloProvider client={client}>
        <MainSection>
          <Component {...pageProps} />
        </MainSection>
      </ApolloProvider>
      <Footer />
    </Wrapper>
  );
}

export default MyApp;
